spring:
  application:
    name: db-service


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
  instance:
    hostname: localhost